[package]
name = "iron-ructe"
version = "0.4.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["sass", "mime02"] }

[dependencies]
iron = "0.6"
router = "0.6"
mime = "~0.2"
