[package]
name = "nickel-ructe"
version = "0.4.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["sass", "mime02"] }

[dependencies]
nickel = "0.11.0"
time = "0.1.42"
mime = "0.2.6"
