[package]
name = "warp-actix"
version = "0.6.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["sass", "mime03"] }

[dependencies]
actix-web = "1.0.2"
mime = "0.3.0"
env_logger = "0.6.0"
