[package]
name = "ed2018"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"
build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["mime03", "sass"] }

[dependencies]
mime = "~0.3"
